import Head from "next/head";
import Link from "next/link";
import AppTitle from "~/components/AppTitle";
import LinkItem from "~/components/LinkItem";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const texts: string[] = [
    "Hello World",
    "My Link App",
    "First Solo Test",
    "hjksagfuefh",
  ];
  return (
    <>
      <Head>
        <title>MyLinkApp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[#001C30]">
        <AppTitle />
        <div className="mt-8 flex h-fit w-2/4 flex-col items-center justify-center rounded-xl bg-gradient-to-br from-[#64CCC5] to-[#DAFFFB]">
          {texts.map((text, idx) => (
            <LinkItem key={idx} write={text} />
          ))}
        </div>
      </main>
    </>
  );
}
